

# Others

  Notch:
    Use:
    Name:
    Description:

  Jeff:
    Use:
    Name:
    Description:

  DinnerBone:
    Use:
    Name:
    Description:

  clonalejandro:
    Use:
    Name:
    Description:

  Magical_PvP:
    Use:
    Name:
    Description:

  md_5:
    Use:
    Name:
    Description:

  Pikachu:
    Use:
    Name:
    Description:

  Spider:
    Use:
    Name:
    Description:

  Zombie:
    Use:
    Name:
    Description:

  Chicken:
    Use:
    Name:
    Description:

  Villager:
    Use:
    Name:
    Description:

  Golem:
    Use:
    Name:
    Description:

  Snowman:
    Use:
    Name:
    Description:

  EnderDragon:
    Use:
    Name:
    Description:

  Witch:
    Use:
    Name:
    Description:

  CaveSpider:
    Use:
    Name:
    Description:

  Creeper:
    Use:
    Name:
    Description:

  Skeleton:
    Use:
    Name:
    Description:

  Whiter:
    Use:
    Name:
    Description:

  WhiterSkeleton:
    Use:
    Name:
    Description:

  Pigman:
    Use:
    Name:
    Description:

  Slime:
    Use:
    Name:
    Description:

  Magmacube:
    Use:
    Name:
    Description:

  Blaze:
    Use:
    Name:
    Description:

  Jellyfish:
    Use:
    Name:
    Description:

  Enderman:
    Use:
    Name:
    Description:

  Squid:
    Use:
    Name:
    Description:

  Herobrine:
    Use:
    Name:
    Description:

  Sun:
    Use:
    Name:
    Description:

  Mario:
    Use:
    Name:
    Description:

  Luigi:
    Use:
    Name:
    Description:

  Bowser:
    Use:
    Name:
    Description:

  Browser:
    Use:
    Name:
    Description:

  Toad:
    Use:
    Name:
    Description:

  Duck:
    Use:
    Name:
    Description:

  Globe:
    Use:
    Name:
    Description:

  Shark:
    Use:
    Name:
    Description:

  Dog:
    Use:
    Name:
    Description:

  Cat:
    Use:
    Name:
    Description:

  Ocelot:
    Use:
    Name:
    Description:

  Parrot:
    Use:
    Name:
    Description:

  Slenderman:
    Use:
    Name:
    Description:

  Rabbit:
    Use:
    Name:
    Description: